import { Product } from "../interfaces";

export const PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Chicken",
    details: "1kg, Priceg",
    price: 5.99,
    image: require("../assets/images/chicken.png"),
    categoryId: "meat",
  },  {
    id: "12",
    name: "Beef Steak",
    details: "500g, Grass-fed",
    price: 12.99,
    image: require("../assets/images/beefsteak.png"),
    categoryId: "meat",
  },
  {
    id: "13",
    name: "Salmon Fillet",
    details: "200g, Wild-caught",
    price: 9.99,
    image: require("../assets/images/salmon.png"),
    categoryId: "meat",
  },
  {
    id: "14",
    name: "Organic Eggs",
    details: "6pcs, Free-range",
    price: 4.50,
    image: require("../assets/images/organic_eggs.png"),
    categoryId: "meat",
  },
  {
    id: "15",
    name: "Avocado",
    details: "1pc, Ripe",
    price: 1.99,
    image: require("../assets/images/avocado.png"),
    categoryId: "fruits",
  },
  {
    id: "16",
    name: "Broccoli",
    details: "500g, Fresh",
    price: 3.29,
    image: require("../assets/images/broccoli.png"),
    categoryId: "fruits",
  },
  {
    id: "17",
    name: "Carrots",
    details: "1kg, Organic",
    price: 2.50,
    image: require("../assets/images/carrots.png"),
    categoryId: "fruits",
  },
  {
    id: "18",
    name: "Sparkling Water",
    details: "1L, Lemon flavor",
    price: 1.79,
    image: require("../assets/images/sparkling_water.png"),
    categoryId: "beverages",
  },
  {
    id: "19",
    name: "Almond Milk",
    details: "1L, Unsweetened",
    price: 3.49,

  {
    id: "2",
    name: "Big Chicken Eggs",
    details: "12pcs, Priceg",
    price: 2.99,
    image: require("../assets/images/bigchickeneggs.png"),
    categoryId: "meat",
  },
  {
    id: "3",
    name: "Bananas",
    details: "7pcs, Priceg",
    price: 4.99,
    image: require("../assets/images/banana.png"),
    categoryId: "fruits",
  },
  {
    id: "4",
    name: "Red Apple",
    details: "1kg, Priceg",
    price: 4.99,
    image: require("../assets/images/freshfruitandveg.png"),
    categoryId: "fruits",
  },
  {
    id: "5",
    name: "Bell Pepper",
    details: "1kg, Priceg",
    price: 3.99,
    image: require("../assets/images/bellpepper.png"),
    categoryId: "fruits",
  },
  {
    id: "6",
    name: "Apple Grape Juice",
    details: "1L, Priceg",
    price: 2.49,
    image: require("../assets/images/applegrapejuice.png"),
    categoryId: "beverages",
  },
  {
    id: "7",
    name: "Orange Juice",
    details: "1L, Priceg",
    price: 2.99,
    image: require("../assets/images/orangejuice.png"),
    categoryId: "beverages",
  },
  {
    id: "8",
    name: "Coca Cola",
    details: "500ml, Priceg",
    price: 1.49,
    image: require("../assets/images/cocacola.png"),
    categoryId: "beverages",
  },
  {
    id: "9",
    name: "Diet Coke",
    details: "500ml, Priceg",
    price: 1.59,
    image: require("../assets/images/dietcoke.png"),
    categoryId: "beverages",
  },
  {
    id: "10",
    name: "Cooking Oil",
    details: "1L, Priceg",
    price: 6.99,
    image: require("../assets/images/cookingoilandghee.png"),
    categoryId: "oil",
  },
  {
    id: "11",
    name: "Mayo",
    details: "500g, Priceg",
    price: 3.99,
    image: require("../assets/images/mayo.png"),
    categoryId: "oil",
  },
];
